config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :categories
  resources :menu_items
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/menu_item.rb
class MenuItem < ApplicationRecord
  has_many :menu_categories, dependent: :destroy
  has_many :categories, through: :menu_categories
  accepts_nested_attributes_for :menu_categories, reject_if: :all_blank, allow_destroy: true

  has_many :order_details

  validates :name, presence: true, uniqueness: true
  validates :description, length: { maximum: 150 }
  validates :price,  presence: true, numericality: { greater_than_or_equal_to: 0.01 }

  def delete_associate_categories
    self.menu_categories.destroy_all
  end
  
  def self.by_letter(letter)
    where("name LIKE ?", "#{letter}%").order(:name)
  end

  def has_category
    add_error_at_least_one_category if self.categories.blank?
  end

  def add_error_at_least_one_category
    self.errors.add(:category, 'must add at least one category')
  end
  
end

app/controllers/menu_items_controller.rb
class MenuItemsController < ApplicationController
  before_action :set_menu_item, only: %i[show edit update destroy]

  protect_from_forgery with: :null_session

  # GET /menu_items or /menu_items.json
  def index
    @menu_items = MenuItem.all

    render json: @menu_items.to_json(include: :menu_categories)
  end

  # GET /menu_items/1 or /menu_items/1.json
  def show
    render json: @menu_item.to_json(include: :menu_categories)
  end

  # GET /menu_items/new
  def new
    @menu_item = MenuItem.new
  end

  # GET /menu_items/1/edit
  def edit; end

  # POST /menu_items or /menu_items.json
  def create
    @menu_item = MenuItem.new(menu_item_params)

    if @menu_item.save
      render json: @menu_item.to_json(include: :menu_categories)
    else
      render json: @menu_item.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /menu_items/1 or /menu_items/1.json
  def update
    @menu_item.delete_associate_categories
    
    if @menu_item.update(menu_item_params)
      render json: @menu_item.to_json(include: :menu_categories)
    else
      render json: @menu_item.errors, status: :unprocessable_entity
    end
  end

  # DELETE /menu_items/1 or /menu_items/1.json
  def destroy
    @menu_item.destroy

    render json: { message: 'Menu Item was successfully destroyed.' }
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_menu_item
    begin  
      @menu_item = MenuItem.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      render json: { message: 'Menu Items not found' }, status: :not_found
    end
  end

  # Only allow a list of trusted parameters through.
  def menu_item_params
    begin
      params.require(:menu_item).permit(:name, :description, :price, menu_categories_attributes: %i[id menu_item_id category_id _destroy])
    rescue ActiveRecord::RecordNotFound
      render json: { message: 'Menu Item not found' }, status: :not_found
    end
  end
end

app/helpers/menu_items_helper.rb
module MenuItemsHelper
end

app/views/menu_items/_form.html.erb
<%= form_with(model: menu_item) do |form| %>
  <% if menu_item.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(menu_item.errors.count, "error") %> prohibited this menu_item from being saved:</h2>

      <ul>
        <% menu_item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>


  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.label :category, style: "display: block" %>
    
    <% Category.all.each do |category| %>
      <input type="checkbox" name="category_ids[]" value=<%= category.id %> />
      <label for=<%= category.id %>><%= category.name %></label><br>
    <% end %>

  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/menu_items/_menu_item.html.erb
<div id="<%= dom_id menu_item %>">
  <p>
    <strong>Name:</strong>
    <%= menu_item.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= menu_item.description %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= menu_item.price %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= menu_item.categories.pluck(:name).join(", ") %>
  </p>

</div>

app/views/menu_items/edit.html.erb
<h1>Editing menu item</h1>

<%= render "form", menu_item: @menu_item %>

<br>

<div>
  <%= link_to "Show this menu item", @menu_item %> |
  <%= link_to "Back to menu items", menu_items_path %>
</div>

app/views/menu_items/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Menu items</h1>

<div id="menu_items">
<!--   <% @menu_items.each do |menu_item| %>
    <%= render menu_item %>
    <p>
      <%= link_to "Show this menu item", menu_item %>
    </p>
  <% end %> -->

  <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Description</th>
        <th scope="col">Price</th>
        <th scope="col">Category</th>
        <th scope="col">Show</th>
        <th scope="col">Edit</th>
        <th scope="col">Delete</th>
      </tr>
    </thead>
    <tbody>
  
    <% @menu_items.each_with_index do |menu_item, index| %>
      <tr>
        <th scope="row"><%= index+1 %></th>
        <td><%= menu_item.name %></td>
        <td><%= menu_item.description %></td>
        <td><%= menu_item.price %></td>
        <td><%= menu_item.categories.pluck(:name).join(", ") %></td>
        <td><%= button_to 'Show', menu_item_path(menu_item), method: 'get' %></td>
        <td><%= button_to 'Edit', edit_menu_item_path(menu_item), method: 'get' %></td>
        <td><%= button_to 'Delete', menu_item_path(menu_item), method: 'delete' %></td>
      </tr>
    <% end %>
  
    </tbody>
  </table>
</div>

<%= link_to "New menu item", new_menu_item_path %>

app/views/menu_items/new.html.erb
<h1>New menu item</h1>

<%= render "form", menu_item: @menu_item %>

<br>

<div>
  <%= link_to "Back to menu items", menu_items_path %>
</div>

app/views/menu_items/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @menu_item %>

<div>
  <%= link_to "Edit this menu item", edit_menu_item_path(@menu_item) %> |
  <%= link_to "Back to menu items", menu_items_path %>

  <%= button_to "Destroy this menu item", @menu_item, method: :delete %>
</div>