config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :categories
  resources :menu_items
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details
  accepts_nested_attributes_for :order_details, reject_if: :all_blank, allow_destroy: true

  enum status: { NEW: 0, PAID: 1, CANCELED: 2 }
  
  validates :customer_name, presence: true
  validates :customer_email,  presence: true, format: { with: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i, message: 'invalid email format' }
  validates :total_price, numericality: { greater_than_or_equal_to: 0.01 }
  validates :status, inclusion: { in: statuses.keys }

  after_initialize :set_defaults, unless: :persisted?

  scope :filter_by_email, ->(customer_email) { customer_email.present? ? where(customer_email: customer_email) : all }
  scope :filter_by_min_total_price, ->(min_total_price) { min_total_price.present? ? where('total_price >= ?', min_total_price.to_f) : all }
  scope :filter_by_max_total_price, ->(max_total_price) { max_total_price.present? ? where('total_price <= ?', max_total_price.to_f) : all }
  scope :filter_by_start_date, ->(start_date) { start_date.present? ? where('created_at >= ?', start_date) : all }
  scope :filter_by_end_date, ->(end_date) { end_date.present? ? where('created_at <= ?', end_date) : all }

  def delete_associate_order_details
    self.order_details.destroy_all
  end

  def set_defaults
    self.order_date ||= DateTime.now
    self.status ||= :NEW
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: %i[ show edit update destroy ]

  protect_from_forgery with: :null_session
  
  # GET /orders or /orders.json
  def index
    @orders = Order
    .filter_by_email(params[:email])
    .filter_by_min_total_price(params[:min_price])
    .filter_by_max_total_price(params[:max_price])
    .filter_by_start_date(params[:start_date])
    .filter_by_end_date(params[:end_date])

    render json: @orders.to_json(:include => :order_details) 
  end

  # GET /orders/1 or /orders/1.json
  def show
    render json: @order.to_json(:include => :order_details)
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders or /orders.json
  def create
    unless menu_item_exist?
      render json: { message: 'Menu Item not found' }, status: :not_found 
      return
    end
  
    calculate_total_price
    
    @order = Order.new(order_params)

    if @order.save
      render json: @order.to_json(:include => :order_details) 
    else
      render json: @order.errors, status: :unprocessable_entity 
    end
  end

  # PATCH/PUT /orders/1 or /orders/1.json
  def update
    unless menu_item_exist?
      return render json: { message: 'Menu Item not found' }, status: :not_found 
    end
    
    status = params[:order][:status]
    unless ["NEW", "PAID", "CANCELED"].include? status
      return render json: { message: " invalid enum status" }, status: :bad_request
    end
    
    @order.delete_associate_order_details
    
    calculate_total_price

    if @order.update(order_params)
      render json: @order.to_json(:include => :order_details)
    else
      render json: @order.errors, status: :unprocessable_entity
    end
  end

  # DELETE /orders/1 or /orders/1.json
  def destroy
    @order.destroy
    render json: { message: 'Order was successfully destroyed.' } 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      begin  
        @order = Order.find(params[:id])
      rescue ActiveRecord::RecordNotFound
        render json: { message: 'Order not found' }, status: :not_found
      end
    end

    def order_params
      params.require(:order).permit(:order_date, :total_price, :customer_name, :customer_email, :status, order_details_attributes: %i[id menu_item_id order_id name price quantity _destroy])
    end

    def calculate_total_price
      total_price = params[:order][:order_details_attributes].map { |order_detail| 

        menu_item = MenuItem.find(order_detail[:menu_item_id])
        
        order_detail[:price] = menu_item.price
        order_detail[:quantity].to_i * order_detail[:price] 
      }.sum
      
      params[:order][:total_price] = total_price
    end

    def menu_item_exist?()
      params[:order][:order_details_attributes].map { |order_detail| 
        begin
          MenuItem.find(order_detail[:menu_item_id])
        rescue ActiveRecord::RecordNotFound
          return false 
        end
        return true
      }
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_with(model: order) do |form| %>
  <% if order.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
        <% order.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :order_date, style: "display: block" %>
    <%= form.datetime_field :order_date %>
  </div>

  <div>
    <%= form.label :total_price, style: "display: block" %>
    <%= form.text_field :total_price %>
  </div>

  <div>
    <%= form.label :customer_name, style: "display: block" %>
    <%= form.text_field :customer_name %>
  </div>

  <div>
    <%= form.label :customer_email, style: "display: block" %>
    <%= form.text_field :customer_email %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.number_field :status %>
  </div>

  <button><%= link_to_add_nested(form, :order_details, '#order-details', link_text: "Add new Order Detail") %></button> <!-- adds a link to add more items -->
  <div id='order-details'>
    <%= form.fields_for :order_details do |order_detail_f| %>
      <%= render 'order_detail_fields', form: order_detail_f %>
    <% end %>
  </div>


  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/orders/_order.html.erb
<div id="<%= dom_id order %>">
  <p>
    <strong>Order date:</strong>
    <%= order.order_date %>
  </p>

  <p>
    <strong>Total price:</strong>
    <%= order.total_price %>
  </p>

  <p>
    <strong>Customer name:</strong>
    <%= order.customer_name %>
  </p>

  <p>
    <strong>Customer email:</strong>
    <%= order.customer_email %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= order.status %>
  </p>

</div>

app/views/orders/_order_detail_fields.html.erb
<div class="wrapper-div">
  <% arr_menu_item = MenuItem.all.map { |menu_item| [menu_item.name + " - Price : " + menu_item.price.to_s, menu_item.id] } %>
  <%= form.label :menu_item_id %>
  <%= select_tag(:menu_item_id,  options_for_select(arr_menu_item)) %>
  <%= form.label :quantity %>
  <%= form.text_field :quantity %>
  <button><%= link_to_remove_nested(form) %></button>
</div>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render "form", order: @order %>

<br>

<div>
  <%= link_to "Show this order", @order %> |
  <%= link_to "Back to orders", orders_path %>
</div>

app/views/orders/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Orders</h1>

<div id="orders">
<!--   <% @orders.each do |order| %>
    <%= render order %>
    <p>
      <%= link_to "Show this order", order %>
    </p>
  <% end %> -->

  <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Order Date</th>
        <th scope="col">Total Price</th>
        <th scope="col">Customer Name</th>
        <th scope="col">Customer Email</th>
        <th scope="col">Status</th>
        <th scope="col">Show</th>
        <th scope="col">Edit</th>
        <th scope="col">Delete</th>
      </tr>
    </thead>
    <tbody>
  
    <% @orders.each_with_index do |order, index| %>
      <tr>
        <th scope="row"><%= index+1 %></th>
        <td><%= order.order_date %></td>
        <td><%= order.total_price %></td>
        <td><%= order.customer_name %></td>
        <td><%= order.customer_email %></td>
        <td><%= order.status %></td>
        <td><%= button_to 'Show', order_path(order), method: 'get' %></td>
        <td><%= button_to 'Edit', edit_order_path(order), method: 'get' %></td>
        <td><%= button_to 'Delete', order_path(order), method: 'delete' %></td>
      </tr>
    <% end %>
  
    </tbody>
  </table>
</div>

<%= link_to "New order", new_order_path %>

app/views/orders/new.html.erb
<h1>New order</h1>

<%= render "form", order: @order %>

<br>

<div>
  <%= link_to "Back to orders", orders_path %>
</div>

app/views/orders/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @order %>

<div>
  <%= link_to "Edit this order", edit_order_path(@order) %> |
  <%= link_to "Back to orders", orders_path %>

  <%= button_to "Destroy this order", @order, method: :delete %>
</div>